#pragma once
#ifndef _RESOURCE_HPP_
#define _RESOURCE_HPP_
namespace dragon
{
	enum class ID_EVENT
	{
		TOOL_PIVOT,
		TOOL_HOVER,
		TOOL_DRAW_EDGE,
		TOOL_DRAW_GRID,
		TOOL_SWITCH_MODE_RENDER,
		CREATE_NEW_RENDER_TARGET,
		MAIN_MENU_HIDE
	};
}
#endif // !_RESOURCE_HPP_